version: '3.8'
services:
  caller:
    container_name: caller
    build:
      context: ./
      dockerfile: Dockerfile 
      args:
        PROJECT_NAME: Caller
    environment:
      CALLER_URL: http://caller
      ISSUER_URL: http://issuer
    ports:
      - "8080:80"
    healthcheck:
      test: curl --fail http://localhost/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped
  issuer:
    container_name: issuer
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: Issuer
    environment:
      VALID_CALLERS: http://caller
      ISSUER_URL: http://issuer
      KNOWN_VERSIONS: HASHBACK-PUBLIC-DRAFT-3-1
      VALID_ROUND_RANGE: 1-99
      ALLOWED_TIME_DRIFT: 10
    healthcheck:
      test: curl --fail http://localhost/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: unless-stopped